# Generated by Django 3.2.12 on 2022-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('user_type', models.CharField(default='default', max_length=10, null=True)),
                ('user_name', models.CharField(default='user', max_length=10)),
                ('user_profile_image', models.CharField(default='1', max_length=255)),
                ('user_notice', models.IntegerField(default=0)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_kakao_id', models.CharField(max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
