# Generated by Django 3.2.12 on 2022-04-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('ranking_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ranking', serialize=False, to='accounts.user')),
                ('ranking_time', models.IntegerField(default=0)),
                ('ranking_day', models.IntegerField(default=0)),
                ('ranking_last_day', models.DateField(auto_now_add=True)),
                ('ranking_consecutive_days', models.IntegerField(default=0)),
                ('ranking_max_consecutive_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('timereport_id', models.AutoField(primary_key=True, serialize=False)),
                ('timereport_day', models.DateField(auto_now_add=True)),
                ('timereport_time', models.IntegerField()),
                ('timereport_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
